<MyScreenManager>:
    FirstScreen:
    SecondScreen:
    ThirdScreen:
    FourthScreen:
    FifthScreen:
    SixthScreen:

<FirstScreen>:
    name: 'first_screen'
    MDFloatLayout:
        mg_bg_color: 1, 1, 1, 1
        Image:
            source: "herramienta-de-audio-con-altavoz.png"
            size_hint: 0.15, 0.15
            pos_hint: {"center_x": 0.5, "center_y": 0.85}
        Image:
            source: "logo.png"
            size_hint: 0.7, 0.7
            pos_hint: {"center_x": 0.5, "center_y": 0.55}
        MDLabel:
            text: "HELPER"
            pos_hint: {"center_x": 0.5, "center_y": 0.70}
            halign: "center"
            font_size: "30sp"
            bold: True
        MDLabel:
            text: "PENCIL"   
            pos_hint: {"center_x": 0.5, "center_y": 0.35}
            halign: "center"
            font_size: "30sp"
            bold: True
        MDLabel:
            text: "by Maiky Jimenez y David Rangel "    
            pos_hint: {"center_x": 0.5, "center_y": 0.24}
            halign: "center"
            font_size: "15sp"
            bold: True

        BoxLayout:
            Button:
                background_color: 0, 0, 0, 0
                text: 'btn'
                size_hint: None, None
                size: root.width * 0.98, root.height * 0.12
                pos: root.width * 0.1, root.height * 0.78
                on_press: app.change_screen('second_screen')
                Image:
                    source: 'flecha-curva-apuntando-a-la-derecha.png'
                    size: self.parent.size
                    allow_stretch: True

        MDLabel:
            text: "2023 Education Project"    
            pos_hint: {"center_x": 0.5, "center_y": 0.06}
            halign: "center"
            font_size: "15sp"
            bold: True

<SecondScreen>:
    name: 'second_screen'
    MDFloatLayout:
        mg_bg_color: 1, 1, 1, 1
        Image:
            source: "logo.png"
            size_hint: 0.8, 0.8
            pos_hint: {"center_x": 0.5, "center_y": 0.75}

        Button:
            text: 'HABLA'
            size_hint: None, None
            size: self.texture_size[0] * 4, self.texture_size[1] * 6
            pos_hint: {"center_x": 0.5, "center_y": 0.6}
            on_press: app.change_screen('third_screen')
        Button:
            text: 'Ir a la Cuarta Pantalla'
            size_hint: None, None
            size: self.texture_size[0] * 1.2, self.texture_size[1] * 1.2
            pos_hint: {"center_x": 0.5, "center_y": 0.4}
            on_press: app.change_screen('fourth_screen')
        Button:
            text: 'Ir a la Cuarta Pantalla'
            size_hint: None, None
            size: self.texture_size[0] * 1.2, self.texture_size[1] * 1.2
            pos_hint: {"center_x": 0.5, "center_y": 0.3}
            on_press: app.change_screen('fourth_screen')
        Button:
            text: 'Ir a la Cuarta Pantalla'
            size_hint: None, None
            size: self.texture_size[0] * 1.2, self.texture_size[1] * 1.2
            pos_hint: {"center_x": 0.5, "center_y": 0.2}
            on_press: app.change_screen('fourth_screen') 



<ThirdScreen>:
    name: 'third_screen'
    # Definición de la tercera pantalla

<FourthScreen>:
    name: 'fourth_screen'
    # Definición de la cuarta pantalla

<FifthScreen>:
    name: 'fifth_screen'
    # Definición de la quinta pantalla

<SixthScreen>:
    name: 'sixth_screen'
    # Definición de la sexta pantalla

